system:
  id_system:                epistematic


###############################################################################
host:
  localhost:
    hostname:               'localhost'
    acct_run:               ''
    acct_provision:         ''
    port_range:             '8080-8199'
    dirpath_log:            ''
    launch_cmd:             ''
    environment:            'e005_ocr_nougat'
    log_level:              'INFO'


###############################################################################
process:
  proc_main:
    host:                   localhost


###############################################################################
node:

  # ---------------------------------------------------------------------------
  # System clock and state management for the entire system.
  #
  ctrl_sys:
    process:                proc_main
    req_host_cfg:           default_configuration
    functionality:
      py_module:            cl.ctrl.sys.ic00_edict
    state_type:             py_dict
    config:
      frequency_hz:         10

  # ---------------------------------------------------------------------------
  # State management for the main process.
  #
  ctrl_main:
    process:                proc_main
    req_host_cfg:           default_configuration
    functionality:
      py_module:            cl.ctrl.proc.ic00_edict
    state_type:             py_dict

  # ---------------------------------------------------------------------------
  # File loader.
  #
  load:
    process:                proc_main
    req_host_cfg:           default_configuration
    functionality:
      py_module:            cl.load.file.ic00_edict
    state_type:             py_dict
    config:
      dirpath_root:
        - /media/wtp/Data1/ref/60_refman/test/
        # - /media/wtp/Data1/ref/00_intray/01_by_year/2013/
        # - /media/wtp/Data1/ref/00_intray/00_triage/
      pathincl:
        - !regex '^.*\.pdf$'
      direxcl:
        - !regex '^\..*$'
        - !regex '^.*\.egg-info$'
        - !regex '^.pytest-cache$'
        - !regex '^\.cache$'
        - !regex '^\.git$'
        - !regex '^\.tox$'
        - !regex '^\.vagrant$'
        - !regex '^__pycache__$'
      read_as_bin:
        - !regex '^.*\.pdf$'
      batch_size:           2
      output_all:           True
      repeat_all:           False
      output_modified:      False
      terminate_when_done:  True

  # ---------------------------------------------------------------------------
  # Epistematic engine.
  #
  engine:
    process:                proc_main
    req_host_cfg:           default_configuration
    functionality:
      py_module:            epistematic.engine.ic00_edict
    state_type:             py_dict


###############################################################################
edge:

  # Control signals

  - owner: ctrl_sys
    data:  py_dict
    src:   ctrl_sys.outputs.ctrl_main
    dst:   ctrl_main.inputs.ctrl

  - owner: ctrl_main
    data:  py_dict
    src:   ctrl_main.outputs.load
    dst:   load.inputs.ctrl

  - owner: ctrl_main
    data:  py_dict
    src:   ctrl_main.outputs.engine
    dst:   engine.inputs.ctrl

  # File pipeline

  - owner: load
    data:  py_dict
    src:   load.outputs.fileinfo
    dst:   engine.inputs.fileinfo


###############################################################################
data:
  py_list:  py_list
  py_dict:  py_dict
  py_str:   py_str


###############################################################################
req_host_cfg:
  default_configuration:
    role:
      - default_role


###############################################################################
role:
  default_role:
    tasks:
      - name: Update apt-get repo and cache
        become:        yes
        become_user:   root
        become_method: sudo
        apt:
          update_cache:     yes
          force_apt_get:    yes
          cache_valid_time: 3600
