title:
  "Environment register"


introduction:
  "This register holds a list of environments and
  the role that each is currently assigned to."


register:

  e000_design_automation_core:
    name: "Design automation core"
    type: "virtualenv"
    desc: "Core virtualenv for core design automation tools."

  e001_process_assistant:
    name: "process assistant"
    type: "virtualenv"
    desc: "Virtualenv for the process assistant system and tools."

  e002_general_research:
    name: "general research"
    type: "virtualenv"
    desc: "Virtualenv for general purpose research and development work."

  e003_discord:
    name: "discord"
    type: "virtualenv"
    desc: "Virtualenv for discord bots with minimal other dependencies."

  e004_reflex:
    name: "reflex"
    type: "virtualenv"
    desc: "Virtualenv for reflex UIs with minimal other dependencies."

  e005_unstructured:
    name: "unstructured"
    type: "virtualenv"
    desc: "Virtualenv for unstructured ETL with minimal other dependencies."
